### ISSUE TITLE
Bug: HLM-BMI get_current_time

### ISSUE THREAD

**Issue by erazocar** [uihilab/HLM-Web#1]
https://github.com/uihilab/HLM-Web/blob/ed660414bde26b01d8adc6bf529abd7f0af0dc22/bmi-version/_src/hlmweb-bmi.js#L512

**Comment by gregjewi** [comment]
@erazocar, I updated get_current_time() to return a JS timestamp -- i.e., milliseconds since the epoch. See here 

https://github.com/uihilab/HLM-Web/blob/27f29bab75acb63c14b89364dd64542e68315c82/bmi-version/_src/hlmweb-bmi.js#L512
